name: ParticleDemo
version: 1.1.0
author: DarkBlade12
website: http://dev.bukkit.org/profiles/DarkBladee12

main: com.darkblade12.particledemo.ParticleDemo

commands:
  particle:
    usage: /<command> help
    aliases: [particledemo, pd]